name: Unit Test Generation Sanity Check

on:
  push:
    branches:
      - main 
  pull_request:
    branches: [ main ]

jobs:
  generator-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
        with:
          submodules: recursive
      - name: Set up system
        run: python3 scripts/setup.py --skip-upgrade
      - name: Generate protobuf files
        run: python3 scripts/generate_protobuf.py
  golang-generator-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Go 1.22.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: installing protoc
        run: sudo apt install -y protobuf-compiler
      - name: Generate protobuf files
        run: ./scripts/generate_go.sh
